### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by WebReflection** [alshdavid/BorrowScript#40]
Likely the very least of this project's priorities, but worth mentioning the SVGs aren't visually great on dark theme.

![Screenshot from 2021-11-12 13-46-26](https://user-images.githubusercontent.com/85749/141469576-fd89431c-44ef-4510-aa65-9219fef4f1f3.png)

**Comment by alshdavid** [comment]
Oh yikes, and there is no way to create adaptive markdown files in GitHub 😓

**Comment by WebReflection** [comment]
No, but there is a way to style within SVG and use [prefers-color-schema](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

```css
svg { fill: #000; }
@media (prefers-color-scheme: dark) {
  svg { fill: #fff; }
}
```

or something similar
